# fly.toml app configuration file generated for src-restless-tree-7683 on 2026-04-25T09:16:42-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'src-restless-tree-7683'
primary_region = 'iad'

[build]

[env]
  KAFKA_BOOTSTRAP = "localhost:9092"
  CLICKHOUSE_HOST = "localhost"
  CLICKHOUSE_PORT = "8123"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.checks]]
    grace_period = "120s"
    interval = "15s"
    method = "GET"
    path = "/"
    timeout = "5s"
    type = "http"

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 2048
